services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000" # Mapear a porta do backend
    volumes:
      - ./backend:/app # Montar o diretório do backend como volume
      - /app/node_modules # Evitar sobrescrever o node_modules dentro do container
    # Conectar ao MongoDB
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Expor a porta padrão do MongoDB
    volumes:
      - mongo-data:/data/db # Persistir dados do MongoDB
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
