services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:8.0-noble
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
